import { Link } from 'react-router-dom'
import { useLanguage } from '../context/LanguageContext'

const content = {
  en: {tag:'Service',title:'Mental Coaching',subtitle:'Build resilience, confidence, and mental clarity through a supportive and goal-oriented process.',what:'What is mental coaching?',p1:'Mental coaching helps you strengthen the mindset and habits that support performance, wellbeing, and everyday life. It can help with confidence, motivation, focus, and emotional resilience.',p2:'Sessions are practical, reflective, and tailored to you. Together, we identify what is getting in your way and what will move you forward.',how:'What can it help with?',list:['Building confidence and self-belief','Managing stress and pressure','Improving focus and motivation','Strengthening emotional resilience','Preparing for change or challenges'],who:'Who is it for?',who1:'Mental coaching is for anyone who wants support in developing their inner resources. Whether you are facing a demanding season, striving toward a goal, or simply wanting to feel stronger and clearer, this approach can help.',who2:'It is suitable for individuals, students, professionals, and anyone seeking practical, supportive growth.',ctaTitle:'Ready to strengthen your mindset?',ctaText:'Let us talk about what support would be most helpful for you.',ctaButton:'Book a Session'},
  fi: {tag:'Palvelu',title:'Mental Coaching',subtitle:'Rakenna resilienssiä, itseluottamusta ja mielen selkeyttä tukevassa ja tavoitteellisessa prosessissa.',what:'Mitä mental coaching on?',p1:'Mental coaching auttaa vahvistamaan ajattelutapaa ja tapoja, jotka tukevat suorituskykyä, hyvinvointia ja arkea. Se voi auttaa esimerkiksi itseluottamuksen, motivaation, keskittymisen ja tunne-elämän resilienssin kehittämisessä.',p2:'Tapaamiset ovat käytännöllisiä, reflektoivia ja juuri sinulle räätälöityjä. Yhdessä tunnistamme, mikä estää etenemistäsi ja mikä vie sinua eteenpäin.',how:'Missä se voi auttaa?',list:['Itseluottamuksen vahvistaminen','Stressin ja paineen hallinta','Keskittymisen ja motivaation kehittäminen','Tunne-elämän resilienssin vahvistaminen','Valmistautuminen muutoksiin tai haasteisiin'],who:'Kenelle se sopii?',who1:'Mental coaching sopii kaikille, jotka haluavat kehittää sisäisiä voimavarojaan. Olitpa vaativassa elämäntilanteessa, etenemässä kohti tavoitetta tai haluamassa lisää selkeyttä ja vahvuutta, tästä voi olla hyötyä.',who2:'Se sopii yksilöille, opiskelijoille, ammattilaisille ja kaikille, jotka kaipaavat käytännöllistä ja kannattelevaa kasvua.',ctaTitle:'Haluatko vahvistaa ajattelutapaasi?',ctaText:'Keskustellaan siitä, millainen tuki olisi sinulle hyödyllisintä.',ctaButton:'Varaa aika'},
  sv: {tag:'Tjänst',title:'Mental coaching',subtitle:'Bygg upp motståndskraft, självförtroende och mental klarhet i en stödjande och målinriktad process.',what:'Vad är mental coaching?',p1:'Mental coaching hjälper dig att stärka det mindset och de vanor som stödjer prestation, välmående och vardagsliv. Det kan hjälpa med självförtroende, motivation, fokus och känslomässig motståndskraft.',p2:'Sessionerna är praktiska, reflekterande och anpassade efter dig. Tillsammans identifierar vi vad som står i vägen och vad som hjälper dig framåt.',how:'Vad kan det hjälpa med?',list:['Bygga självförtroende och tillit till dig själv','Hantera stress och press','Förbättra fokus och motivation','Stärka känslomässig motståndskraft','Förbereda dig för förändring eller utmaningar'],who:'Vem passar det för?',who1:'Mental coaching passar alla som vill utveckla sina inre resurser. Oavsett om du befinner dig i en krävande period, strävar mot ett mål eller bara vill känna dig starkare och klarare kan detta vara ett bra stöd.',who2:'Det passar individer, studerande, yrkesverksamma och andra som söker praktisk och stödjande utveckling.',ctaTitle:'Redo att stärka ditt mindset?',ctaText:'Låt oss prata om vilket stöd som skulle vara mest hjälpsamt för dig.',ctaButton:'Boka en tid'},
}

export default function MentalCoaching(){const { language }=useLanguage(); const t=content[language]; return (<>
<section className="page-hero"><div className="container"><span className="section-header__tag fade-in">{t.tag}</span><h1 className="page-hero__title fade-in fade-in-delay-1">{t.title}</h1><p className="page-hero__subtitle fade-in fade-in-delay-2">{t.subtitle}</p></div></section>
<section className="section"><div className="container"><div className="content-block"><div className="content-block__visual fade-in">🧠</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.what}</h2><p>{t.p1}</p><p>{t.p2}</p></div></div></div></section>
<section className="section section--alt"><div className="container"><div className="content-block content-block--reverse"><div className="content-block__visual fade-in">⚡</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.how}</h2><ul>{t.list.map((item)=><li key={item}>{item}</li>)}</ul></div></div></div></section>
<section className="section"><div className="container"><div className="content-block"><div className="content-block__visual fade-in">🌟</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.who}</h2><p>{t.who1}</p><p>{t.who2}</p></div></div></div></section>
<section className="section"><div className="container"><div className="cta-banner fade-in"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><Link to="/contact" className="btn btn--primary">{t.ctaButton}</Link></div></div></section>
</>)}
