import { Link } from 'react-router-dom'
import { useLanguage } from '../context/LanguageContext'

const content={
 en:{tag:'Pricing',title:'Transparent, fair pricing',subtitle:'Investing in yourself is one of the most valuable things you can do. Our pricing is clear and straightforward.',plans:[['Online Session','Coaching or therapy from the comfort of your own space.','€50','/ session','45 minutes',['Video call via a secure platform','Flexible scheduling','Available for all service types','Suitable for follow-up sessions'],'Book Online Session','outline'],['In-Person Session','Face-to-face coaching in a calm, welcoming environment.','€60','/ session','60 minutes',['Private, comfortable setting','Full hour of dedicated time','Available for all service types','Includes animal-assisted options'],'Book In-Person Session','primary'],['Introductory Call','A free, no-obligation conversation to see if we are a good fit.','Free','','15–20 minutes',['Get to know each other','Discuss your needs and goals','Ask any questions you have','No commitment required'],'Schedule Free Call','outline']],good:'Good to Know',faq:'Frequently asked questions',qs:[['📅','How do I schedule?','Use our contact form or reach out by email. We will find a time that works for both of us.'],['🔄','Can I cancel or reschedule?','Yes — we ask for at least 24 hours’ notice for cancellations or rescheduling.'],['💳','How do I pay?','Payment details are shared after booking. We accept bank transfer and common online payment methods.']],ctaTitle:'Questions about pricing?',ctaText:'We are happy to discuss options. Reach out anytime.',ctaButton:'Contact Us'},
 fi:{tag:'Hinnasto',title:'Selkeä ja reilu hinnoittelu',subtitle:'Itsesi tukeminen on yksi arvokkaimmista investoinneista, joita voit tehdä. Hinnoittelumme on selkeä ja suoraviivainen.',plans:[['Etätapaaminen','Coachingia tai terapiaa omasta rauhallisesta ympäristöstäsi.','€50','/ tapaaminen','45 minuuttia',['Videopuhelu turvallisen alustan kautta','Joustava ajanvaraus','Saatavilla kaikkiin palveluihin','Sopii myös jatkotapaamisiin'],'Varaa etätapaaminen','outline'],['Lähitapaaminen','Kasvokkainen coaching rauhallisessa ja lämpimässä ympäristössä.','€60','/ tapaaminen','60 minuuttia',['Yksityinen ja mukava tila','Täysi tunti omistettua aikaa','Saatavilla kaikkiin palveluihin','Mahdollisuus eläinavusteisiin vaihtoehtoihin'],'Varaa lähitapaaminen','primary'],['Alkukeskustelu','Maksuton ja sitoumukseton keskustelu yhteensopivuuden arvioimiseksi.','Maksuton','','15–20 minuuttia',['Tutustutaan toisiimme','Käydään läpi tarpeesi ja tavoitteesi','Voit esittää kysymyksiä','Ei sitoutumispakkoa'],'Varaa maksuton puhelu','outline']],good:'Hyvä tietää',faq:'Usein kysytyt kysymykset',qs:[['📅','Miten varaan ajan?','Voit käyttää yhteydenottolomaketta tai lähettää sähköpostia. Etsimme yhdessä sopivan ajan.'],['🔄','Voinko perua tai siirtää ajan?','Kyllä — pyydämme vähintään 24 tunnin ilmoituksen peruutuksista tai siirroista.'],['💳','Miten maksu tapahtuu?','Maksutiedot toimitetaan varauksen jälkeen. Hyväksymme tilisiirron ja yleiset verkkomaksutavat.']],ctaTitle:'Kysymyksiä hinnoittelusta?',ctaText:'Keskustelemme mielellämme vaihtoehdoista. Ota yhteyttä milloin vain.',ctaButton:'Ota yhteyttä'},
 sv:{tag:'Priser',title:'Transparent och rättvis prissättning',subtitle:'Att investera i sig själv är en av de mest värdefulla sakerna du kan göra. Våra priser är tydliga och enkla.',plans:[['Online-session','Coaching eller terapi från tryggheten i ditt eget utrymme.','€50','/ session','45 minuter',['Videosamtal via en säker plattform','Flexibel bokning','Tillgänglig för alla tjänster','Passar bra för uppföljande sessioner'],'Boka online-session','outline'],['Session på plats','Personlig coaching i en lugn och välkomnande miljö.','€60','/ session','60 minuter',['Privat och bekväm miljö','En hel timme med fullt fokus','Tillgänglig för alla tjänster','Inkluderar djurassisterade alternativ'],'Boka session på plats','primary'],['Inledande samtal','Ett kostnadsfritt samtal utan förpliktelser för att se om vi passar ihop.','Gratis','','15–20 minuter',['Lär känna varandra','Diskutera dina behov och mål','Ställ dina frågor','Ingen förpliktelse krävs'],'Boka gratis samtal','outline']],good:'Bra att veta',faq:'Vanliga frågor',qs:[['📅','Hur bokar jag?', 'Använd vårt kontaktformulär eller hör av dig via e-post. Vi hittar en tid som passar oss båda.'],['🔄','Kan jag avboka eller boka om?', 'Ja — vi ber om minst 24 timmars framförhållning vid avbokning eller ombokning.'],['💳','Hur betalar jag?', 'Betalningsuppgifter delas efter bokning. Vi accepterar banköverföring och vanliga onlinebetalningsmetoder.']],ctaTitle:'Frågor om priser?',ctaText:'Vi pratar gärna om olika alternativ. Hör av dig när som helst.',ctaButton:'Kontakta oss'},
}

export default function Pricing(){const { language }=useLanguage(); const t=content[language]; return (<>
<section className="page-hero"><div className="container"><span className="section-header__tag fade-in">{t.tag}</span><h1 className="page-hero__title fade-in fade-in-delay-1">{t.title}</h1><p className="page-hero__subtitle fade-in fade-in-delay-2">{t.subtitle}</p></div></section>
<section className="section"><div className="container"><div className="pricing-grid">{t.plans.map((plan,index)=><div className={`pricing-card ${plan[7]==='primary'?'pricing-card--featured':''} fade-in fade-in-delay-${index+1}`} key={plan[0]}><h3 className="pricing-card__title">{plan[0]}</h3><p className="pricing-card__desc">{plan[1]}</p><div className="pricing-card__price">{plan[2]} <span>{plan[3]}</span></div><p className="pricing-card__duration">{plan[4]}</p><ul className="pricing-card__features">{plan[5].map((item)=><li key={item}>{item}</li>)}</ul><Link to="/contact" className={`btn ${plan[7]==='primary'?'btn--primary':'btn--outline'}`} style={{ width: '100%', textAlign: 'center' }}>{plan[6]}</Link></div>)}</div></div></section>
<section className="section section--alt"><div className="container"><div className="section-header text-center fade-in"><span className="section-header__tag">{t.good}</span><h2 className="section-header__title">{t.faq}</h2></div><div className="values-grid">{t.qs.map((q,index)=><div className={`value-card fade-in fade-in-delay-${index+1}`} key={q[1]}><div className="value-card__icon">{q[0]}</div><h3>{q[1]}</h3><p>{q[2]}</p></div>)}</div></div></section>
<section className="section"><div className="container"><div className="cta-banner fade-in"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><Link to="/contact" className="btn btn--primary">{t.ctaButton}</Link></div></div></section>
</>)}
