import { Link } from 'react-router-dom'
import { useLanguage } from '../context/LanguageContext'

const content={
 en:{tag:'Service',title:'Solution-Focused Brief Therapy',subtitle:'Short-term therapeutic support centred on strengths, goals, and meaningful change.',what:'What is solution-focused brief therapy?',p1:'Solution-Focused Brief Therapy is an evidence-based therapeutic approach that concentrates on solutions rather than problems. It is designed to help you move forward efficiently while respecting your strengths and autonomy.',p2:'Most courses of therapy involve only a few sessions. The focus stays on what you want to be different and what steps will help you get there.',how:'How is it different from coaching?',p3:'While coaching focuses on growth and goals, brief therapy is better suited when emotional distress or deeper psychological challenges are part of the picture.',list:['Evidence-based framework','Focuses on what you want, not what went wrong','Often works within 3–8 sessions','Suitable for a wide range of concerns','Empowering and respectful'],right:'Is it right for me?',p4:'This can help with anxiety, low mood, relationship difficulties, grief, stress, and life transitions. If you want professional support without committing to years of therapy, it may be a good fit.',p5:'If you are unsure whether coaching or therapy would suit you better, we can discuss that together in an introductory conversation.',ctaTitle:'Change does not have to take forever',ctaText:'A few focused sessions can make a real difference.',ctaButton:'Book a Session'},
 fi:{tag:'Palvelu',title:'Ratkaisukeskeinen lyhytterapia',subtitle:'Lyhytkestoista terapeuttista tukea, jonka keskiössä ovat vahvuudet, tavoitteet ja merkityksellinen muutos.',what:'Mitä ratkaisukeskeinen lyhytterapia on?',p1:'Ratkaisukeskeinen lyhytterapia on näyttöön perustuva terapeuttinen lähestymistapa, joka keskittyy ratkaisuihin ongelmien sijaan. Sen tavoitteena on auttaa sinua etenemään tehokkaasti vahvuuksiasi ja autonomiaasi kunnioittaen.',p2:'Usein terapiaprosessi koostuu vain muutamasta tapaamisesta. Huomio pidetään siinä, mitä haluat elämässäsi muuttuvan ja mitkä askeleet vievät sinua siihen suuntaan.',how:'Miten se eroaa coachingista?',p3:'Coaching painottuu kasvuun ja tavoitteisiin, kun taas lyhytterapia sopii paremmin tilanteisiin, joissa mukana on kuormitusta, tunnehaasteita tai syvempiä psykologisia teemoja.',list:['Näyttöön perustuva viitekehys','Keskittyy siihen mitä haluat, ei siihen mikä meni pieleen','Usein 3–8 tapaamista','Sopii monenlaisiin elämäntilanteisiin','Voimaannuttava ja kunnioittava'],right:'Sopiiko tämä minulle?',p4:'Tämä voi auttaa esimerkiksi ahdistuksessa, alakuloisuudessa, ihmissuhdehaasteissa, surussa, stressissä ja elämänmuutoksissa. Jos haluat ammatillista tukea ilman vuosien terapiaprosessia, tämä voi olla hyvä vaihtoehto.',p5:'Jos et ole varma sopiiko coaching vai terapia paremmin tilanteeseesi, voimme pohtia sitä yhdessä alkukeskustelussa.',ctaTitle:'Muutoksen ei tarvitse kestää ikuisesti',ctaText:'Muutama fokusoitu tapaaminen voi tehdä todellisen eron.',ctaButton:'Varaa aika'},
 sv:{tag:'Tjänst',title:'Lösningsfokuserad korttidsterapi',subtitle:'Kortvarigt terapeutiskt stöd med fokus på styrkor, mål och meningsfull förändring.',what:'Vad är lösningsfokuserad korttidsterapi?',p1:'Lösningsfokuserad korttidsterapi är en evidensbaserad terapeutisk metod som fokuserar på lösningar snarare än problem. Den är utformad för att hjälpa dig framåt på ett effektivt sätt med respekt för dina styrkor och din autonomi.',p2:'Ofta omfattar processen bara några få sessioner. Fokus ligger på vad du vill ska bli annorlunda och vilka steg som hjälper dig dit.',how:'Hur skiljer det sig från coaching?',p3:'Coaching fokuserar främst på utveckling och mål, medan korttidsterapi passar bättre när känslomässig belastning eller djupare psykologiska utmaningar finns med i bilden.',list:['Evidensbaserad ram','Fokus på det du vill uppnå, inte bara på det som gått fel','Ofta 3–8 sessioner','Passar många olika bekymmer','Stärkande och respektfullt'],right:'Passar det mig?',p4:'Detta kan hjälpa vid ångest, nedstämdhet, relationssvårigheter, sorg, stress och livsförändringar. Om du vill ha professionellt stöd utan att binda dig till år av terapi kan det vara ett bra alternativ.',p5:'Om du är osäker på om coaching eller terapi passar dig bäst kan vi prata om det i ett inledande samtal.',ctaTitle:'Förändring behöver inte ta för evigt',ctaText:'Några fokuserade sessioner kan göra verklig skillnad.',ctaButton:'Boka en tid'},
}

export default function SolutionFocusedBriefTherapy(){const { language }=useLanguage(); const t=content[language]; return (<>
<section className="page-hero"><div className="container"><span className="section-header__tag fade-in">{t.tag}</span><h1 className="page-hero__title fade-in fade-in-delay-1">{t.title}</h1><p className="page-hero__subtitle fade-in fade-in-delay-2">{t.subtitle}</p></div></section>
<section className="section"><div className="container"><div className="content-block"><div className="content-block__visual fade-in">💬</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.what}</h2><p>{t.p1}</p><p>{t.p2}</p></div></div></div></section>
<section className="section section--alt"><div className="container"><div className="content-block content-block--reverse"><div className="content-block__visual fade-in">🌈</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.how}</h2><p>{t.p3}</p><ul>{t.list.map((item)=><li key={item}>{item}</li>)}</ul></div></div></div></section>
<section className="section"><div className="container"><div className="content-block"><div className="content-block__visual fade-in">🛡️</div><div className="content-block__body fade-in fade-in-delay-1"><h2>{t.right}</h2><p>{t.p4}</p><p>{t.p5}</p></div></div></div></section>
<section className="section"><div className="container"><div className="cta-banner fade-in"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><Link to="/contact" className="btn btn--primary">{t.ctaButton}</Link></div></div></section>
</>)}
