GET http://localhost:3000/api/services/neuropsychiatric-coaching

# Options (based on mongo documents as found in MongoDB-content-examples in the root folder):

# neuropsychiatric-coaching
# solution-focused-coaching
# solution-focused-brief-therapy
# animal-assisted-coaching